services:
  php:
    container_name: {{project-name}}_php
    build:
      args:
        user: rechi
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: landing-app
    restart: always
    working_dir: /var/www/
    volumes:
      - .{{project-folder}}/:/var/www
      - ./docker/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ~/.ssh:/tmp/ssh-keys
    # COPIA A CHAVE SSH DA SUA MÁQUINA LOCAL PARA A PASTA CORRETA
    command: bash -c "
      cp /tmp/ssh-keys/* ~/.ssh && chmod 600 ~/.ssh/* &&
      php-fpm"
    networks:
      - base_network

  nginx:
    container_name: {{project-name}}_nginx
    hostname: {{project-name}}.localhost
    image: nginx:alpine
    restart: always
    volumes:
      - .{{project-folder}}/:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./docker/logs/:/var/log/nginx/
    networks:
      - base_network
      
networks:
  base_network:
    external: true
